default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <% if ENV['DATABASE_URL'].present? %>
  url: <%= ENV['DATABASE_URL'] %>
  <% else %>
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: app_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  <% end %>
